// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalDGC.DataAccess.Data;

#nullable disable

namespace PortalDGC.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalDGC.Domain.Entities.ApoyoNecesario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LlamadoId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LlamadoId");

                    b.ToTable("ApoyosNecesarios");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.ApoyoSolicitado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApoyoId")
                        .HasColumnType("int");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("int");

                    b.Property<string>("Justificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApoyoId");

                    b.HasIndex("InscripcionId");

                    b.ToTable("ApoyosSolicitados");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.AutodefinicionLey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsAfrodescendiente")
                        .HasColumnType("bit");

                    b.Property<bool>("EsTrans")
                        .HasColumnType("bit");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("int");

                    b.Property<bool>("TieneDiscapacidad")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("InscripcionId")
                        .IsUnique();

                    b.ToTable("AutodefinicionesLey");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.Constancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Archivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Validado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PostulanteId");

                    b.ToTable("Constancias");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<int>("LlamadoId")
                        .HasColumnType("int");

                    b.Property<int?>("PosicionOrdenamiento")
                        .HasColumnType("int");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("int");

                    b.Property<decimal>("PuntajeTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("LlamadoId");

                    b.HasIndex("PostulanteId", "LlamadoId")
                        .IsUnique();

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.ItemPuntuable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LlamadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PuntajeMaximo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("LlamadoId");

                    b.ToTable("ItemsPuntuables");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.Llamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bases")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CantidadPuestos")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PorcentajeAfrodescendiente")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PorcentajeDiscapacidad")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PorcentajeTrans")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Llamados");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.LlamadoDepartamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadPuestos")
                        .HasColumnType("int");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<int>("LlamadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("LlamadoId");

                    b.ToTable("LlamadoDepartamentos");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.MeritoPostulante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentoRespaldo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("int");

                    b.Property<int>("ItemPuntuableId")
                        .HasColumnType("int");

                    b.Property<decimal>("PuntajeObtenido")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("Verificado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("InscripcionId");

                    b.HasIndex("ItemPuntuableId");

                    b.ToTable("MeritosPostulante");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.Postulante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CedulaIdentidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DocumentoCedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneroOtro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CedulaIdentidad")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Postulantes");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.RequisitoExcluyente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LlamadoId")
                        .HasColumnType("int");

                    b.Property<bool>("Obligatorio")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LlamadoId");

                    b.ToTable("RequisitosExcluyentes");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.RequisitoPostulante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cumple")
                        .HasColumnType("bit");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequisitoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InscripcionId");

                    b.HasIndex("RequisitoId");

                    b.ToTable("RequisitosPostulante");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.ApoyoNecesario", b =>
                {
                    b.HasOne("PortalDGC.Domain.Entities.Llamado", "Llamado")
                        .WithMany("ApoyosNecesarios")
                        .HasForeignKey("LlamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Llamado");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.ApoyoSolicitado", b =>
                {
                    b.HasOne("PortalDGC.Domain.Entities.ApoyoNecesario", "Apoyo")
                        .WithMany("ApoyosSolicitados")
                        .HasForeignKey("ApoyoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalDGC.Domain.Entities.Inscripcion", "Inscripcion")
                        .WithMany("ApoyosSolicitados")
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apoyo");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.AutodefinicionLey", b =>
                {
                    b.HasOne("PortalDGC.Domain.Entities.Inscripcion", "Inscripcion")
                        .WithOne("AutodefinicionLey")
                        .HasForeignKey("PortalDGC.Domain.Entities.AutodefinicionLey", "InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.Constancia", b =>
                {
                    b.HasOne("PortalDGC.Domain.Entities.Postulante", "Postulante")
                        .WithMany("Constancias")
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.Inscripcion", b =>
                {
                    b.HasOne("PortalDGC.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Inscripciones")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalDGC.Domain.Entities.Llamado", "Llamado")
                        .WithMany("Inscripciones")
                        .HasForeignKey("LlamadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalDGC.Domain.Entities.Postulante", "Postulante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Llamado");

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.ItemPuntuable", b =>
                {
                    b.HasOne("PortalDGC.Domain.Entities.Llamado", "Llamado")
                        .WithMany("ItemsPuntuables")
                        .HasForeignKey("LlamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Llamado");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.LlamadoDepartamento", b =>
                {
                    b.HasOne("PortalDGC.Domain.Entities.Departamento", "Departamento")
                        .WithMany("LlamadoDepartamentos")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalDGC.Domain.Entities.Llamado", "Llamado")
                        .WithMany("LlamadoDepartamentos")
                        .HasForeignKey("LlamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Llamado");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.MeritoPostulante", b =>
                {
                    b.HasOne("PortalDGC.Domain.Entities.Inscripcion", "Inscripcion")
                        .WithMany("MeritosPostulante")
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalDGC.Domain.Entities.ItemPuntuable", "ItemPuntuable")
                        .WithMany("MeritosPostulante")
                        .HasForeignKey("ItemPuntuableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inscripcion");

                    b.Navigation("ItemPuntuable");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.RequisitoExcluyente", b =>
                {
                    b.HasOne("PortalDGC.Domain.Entities.Llamado", "Llamado")
                        .WithMany("RequisitosExcluyentes")
                        .HasForeignKey("LlamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Llamado");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.RequisitoPostulante", b =>
                {
                    b.HasOne("PortalDGC.Domain.Entities.Inscripcion", "Inscripcion")
                        .WithMany("RequisitosPostulante")
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalDGC.Domain.Entities.RequisitoExcluyente", "Requisito")
                        .WithMany("RequisitosPostulante")
                        .HasForeignKey("RequisitoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inscripcion");

                    b.Navigation("Requisito");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.ApoyoNecesario", b =>
                {
                    b.Navigation("ApoyosSolicitados");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("LlamadoDepartamentos");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.Inscripcion", b =>
                {
                    b.Navigation("ApoyosSolicitados");

                    b.Navigation("AutodefinicionLey");

                    b.Navigation("MeritosPostulante");

                    b.Navigation("RequisitosPostulante");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.ItemPuntuable", b =>
                {
                    b.Navigation("MeritosPostulante");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.Llamado", b =>
                {
                    b.Navigation("ApoyosNecesarios");

                    b.Navigation("Inscripciones");

                    b.Navigation("ItemsPuntuables");

                    b.Navigation("LlamadoDepartamentos");

                    b.Navigation("RequisitosExcluyentes");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.Postulante", b =>
                {
                    b.Navigation("Constancias");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("PortalDGC.Domain.Entities.RequisitoExcluyente", b =>
                {
                    b.Navigation("RequisitosPostulante");
                });
#pragma warning restore 612, 618
        }
    }
}
